# Generated by Django 3.1.3 on 2021-01-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=100, verbose_name='Задача')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
                ('is_closed', models.BooleanField(default=False, verbose_name='Выполнена')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Избранная')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
            },
        ),
    ]
