# Generated by Django 3.1.3 on 2021-01-17 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookStore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='Заголовок')),
                ('subtitle', models.CharField(max_length=50, verbose_name='Подзаголовок')),
                ('description', models.CharField(max_length=650, verbose_name='Описание')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('genre', models.CharField(max_length=60, verbose_name='Жанр')),
                ('author', models.CharField(max_length=35, verbose_name='Автор')),
                ('year', models.DateField(verbose_name='Год выхода книги')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Добавление книги на сайт')),
            ],
        ),
    ]
