# Generated by Django 3.1.3 on 2021-01-18 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210118_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='year',
            field=models.DateTimeField(verbose_name='Год выхода книги'),
        ),
    ]
