# Generated by Django 3.1.3 on 2021-01-18 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210118_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookstore',
            name='is_favorite',
            field=models.BooleanField(default=False, verbose_name='Израбнная'),
        ),
        migrations.AlterField(
            model_name='bookstore',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
